replicaCount: 1

image:
  repository: cloudflare/cloudflared
  tag: 2026.6.1
  pullPolicy: IfNotPresent

tunnelTokenSecretName: cloudflare-tunnel-token

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi