apiVersion: batch/v1
kind: CronJob
metadata:
  name: get-usace-levels-cronjob
spec:
  schedule: {{ default "0 0 * * 1" .Values.getusacelevels.schedule | quote }}  # quote the cron string
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}   # 12 spaces here (not 4)
          {{- end }}
          containers:
            - name: get-usace-levels
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
              env:
                - name: MONGO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.mongoCredentialsName | quote }}
                      key: username
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.mongoCredentialsName | quote }}
                      key: password
                - name: MONGO_HOST
                  value: {{ .Values.global.MONGO_HOST | quote }}
                - name: MONGO_PORT
                  value: {{ .Values.global.MONGO_PORT | quote }}
                - name: MONGO_DB
                  value: {{ .Values.global.MONGO_DB | quote }}
                - name: AUTH_SOURCE
                  value: {{ .Values.global.AUTH_SOURCE | quote }}
                - name: DAM_CODES_COLLECTION
                  value: {{ default .Values.getusacelevels.MONGO_COLLECTION .Values.getusacelevels.DAM_CODES_COLLECTION | quote }}
              args: ["getUSACE_levels.js"]
          restartPolicy: OnFailure
