apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-watch-ui
  labels:
    app: flow-watch-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flow-watch-ui
  template:
    metadata:
      labels:
        app: flow-watch-ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: flow-watch-ui
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: {{ .Values.env.PORT | quote }}
        - name: REACT_APP_API_HOST
          value: {{ .Values.env.REACT_APP_API_HOST | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 2
