apiVersion: v1
kind: Service
metadata:
  name: flow-watch-ui
  labels:
    app: flow-watch-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: flow-watch-ui
