replicaCount: 1

imagePullSecrets: []

image:
  repository: docker.io/dstrimble83/flow-watch-service
  tag: latest
  pullPolicy: IfNotPresent

secrets:
  mongoCredentialsName: mongo-credentials
  openaiApiKeyName: ""

service:
  type: ClusterIP
  port: 3000
  name: schedule-service

env:
  MONGO_HOST: flow-watch-mongodb.flow-watch.svc.cluster.local
  MONGO_PORT: 27017
  MONGO_DB: flow-watch
  MONGO_COLLECTION: swpa_schedule
  DAM_CODES_COLLECTION: dam_codes
  AUTH_SOURCE: admin
  PORT: 3000
  contextPath: /schedule
  CORS_URL: https://flow-watch.trimblebarra.com

ingress:
  enabled: false
  className: nginx
  host: flow-watch-api.trimblebarra.com
  tls:
    - hosts:
        - flow-watch-api.trimblebarra.com
      secretName: flow-watch-api-trimblebarra-com
  annotations:
    cert-manager.io/cluster-issuer: production
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"