replicaCount: 1

imagePullSecrets: []

image:
  repository: docker.io/dstrimble83/flow-watch-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  name: flow-watch-ui

env:
  PORT: 80
  REACT_APP_API_HOST: https://flow-watch-api.trimblebarra.com

ingress:
  enabled: false
  className: nginx
  host: flow-watch.trimblebarra.com
  tls:
    - hosts:
        - flow-watch.trimblebarra.com
      secretName: flow-watch-trimblebarra-com
  annotations:
    cert-manager.io/cluster-issuer: production
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"